# Padrões de Limpeza - Versão Simplificada
version = "4.1.0"

[metadados_processuais]
patterns = [
    "Processo:\\s*[\\d\\.-]+",
    "Movimentaca[oã]o?\\s+\\d+\\s*:\\s*\\w+",
    "Arquivo\\s+\\d+\\s*:\\s*[\\w_]+\\.pdf",
    "Usuário:\\s*.+?-\\s*Data:\\s*\\d{2}/\\d{2}/\\d{4}\\s+\\d{2}:\\d{2}:\\d{2}",
    "[A-ZÀ-Ú][A-ZÀ-Ú\\s]+-\\s*VARA\\s+[A-ZÀ-Ú]+",
    "PROCESSO\\s+CRIMINAL\\s*->\\s*Procedimentos\\s+Investigatórios\\s*->\\s*Inquérito\\s+Policial",
    "PROCESSO\\s+CRIMINAL\\s*->\\s*Procedimento\\s+Comum\\s*->\\s*Ação\\s+Penal\\s*-\\s*Procedimento\\s+Ordinário",
    "Valor:\\s*R\\$\\s*\\d*"
]

[assinaturas_digitais]
patterns = [
    "Tribunal\\s+de\\s+Justiça\\s+do\\s+Estado\\s+de\\s+Goiás",
    "Documento\\s+Assinado\\s+e\\s+Publicado\\s+Digitalmente\\s+em\\s+\\d{2}/\\d{2}/\\d{4}\\s+\\d{2}:\\d{2}:\\d{2}",
    "Assinado\\s+por\\s+[A-ZÀ-Ú\\s]+",
    "Localizar\\s+pelo\\s+código:\\s*\\d+,\\s*no\\s+endereço:\\s*https?://[^\\s]+",
    "código:\\s*\\d+,\\s*no\\s+endereço:",
    ":\\s*\\d{15,},\\s*no\\s+endereço:",
    "\\d{15,}",
    "https?://projudi\\.tjgo\\.jus\\.br\\S*"
]

[cabecalhos_institucionais]
patterns = [
    "ESTADO\\s+DE\\s+GOIÁS",
    "SECRETARIA\\s+DE\\s+ESTADO\\s+DA\\s+SEGURANÇA\\s+PÚBLICA",
    "POLÍCIA\\s+CIVIL",
    "REGISTRO\\s+DE\\s+ATENDIMENTO\\s+INTEGRADO",
    "Nº\\s*\\d+",
    "EMITIDO\\s+EM\\s+\\d{2}/\\d{2}/\\d{4}\\s+às\\s+\\d{1,2}:\\d{2}"
]


# ===============================================================
# TEXTOS ROTACIONADOS NAS MARGENS
# ===============================================================

[textos_margem_rotacionados]
description = "Remove textos que aparecem rotacionados nas margens laterais"
patterns = [
    # 1) Assinatura lateral completa
    '''^\s*ASSINATURAS?\s*\|\s*(?:[A-ZÀ-Ü]{2,}(?:\s+(?:DA|DE|DO|DAS|DOS))?){2,6}\s+[0-3]?\d/[01]?\d/(?:\d{2}|\d{4})\s+(?:[01]?\d|2[0-3]):[0-5]\d(?:[:][0-5]\d)?\s*$''',
    # 1.1) Fallback para assinatura quebrada
    '''^\s*ASSINATURAS?\s*\|\s*[A-ZÀ-Ü]{2,}(?:\s+[A-ZÀ-Ü]{2,}){1,}\s*$''',
    # 2) Numeração lateral de páginas
    '''^\s*\d{1,3}/\d{1,3}\s+\d{4,5}\s*$''',
    # 3) Vara e comarca
    '''^\s*[A-ZÀ-Ü]{3,}\s*-\s*VARA\s+[A-ZÀ-Ü]{3,}\s*$''',
    # 4) Usuário e data
    '''^\s*Usu[áa]rio:\s*.+?-\s*Data:\s*[0-3]?\d/[01]?\d/\d{4}\s+(?:[01]?\d|2[0-3]):[0-5]\d:[0-5]\d\s*$''',
    # 5) Valor monetário
    '''^\s*Valor:\s*R\$\s*\d{1,3}(?:\.\d{3})*(?:,\d{2})?\s*$''',
    # 6) Número de processo CNJ
    '''^\s*\d{7}-\d{2}\.\d{4}\.\d\.\d{2}\.\d{4}\s*$''',
]

# ===============================================================
# RODAPÉS INSTITUCIONAIS E CARIMBOS DE SISTEMAS
# ===============================================================

[rodape_institucional]
description = "Remove endereços, contatos e carimbos de sistemas no final das páginas"
patterns = [
    # Endereço completo (RUA + número + CEP + cidade + estado)
    '''RUA\s+[\w\s]+,\s*n[°º]\.\s*\d+,\s*\d{8},\s*[A-ZÀ-Ú\s]+,\s*[A-ZÀ-Ú\s]+,\s*GO''',
    # Linha de telefone e email juntos
    '''Telefone:\s*\d{2}\s*\d{8}\s*/\s*E-mail:\s*[\w\.-]+@[\w\.-]+''',
    # URLs da polícia civil
    '''https?://(?:www\.)?policiacivil\.go\.gov\.br\S*''',
    # Assinatura eletrônica com token (linha completa)
    '''Documento\s+assinado\s+eletronicamente\s+por\s+[A-ZÀ-Ú\s]+,\s*[A-ZÀ-Ú\s]+,\s*em\s+\d{2}/\d{2}/\d{4}\s+\d{2}:\d{2}\.?\s*Token\s+de\s+celular\s+verificado,\s*sob\s+o\s+código\s+[a-f0-9-]+\s*\.?''',

    # Assinatura eletrônica (formato simplificado)
    '''Documento\s+assinado\s+eletronicamente\s+por\s+[^,]+,\s*[^,]+,\s*em\s+\d{2}/\d{2}/\d{4}\s+\d{2}:\d{2}''',
    # Token de celular (caso venha em linha separada)
    '''Token\s+de\s+celular\s+verificado,\s*sob\s+o\s+código\s+[a-f0-9-]+''',
    # Observação sobre impressões digitais (captura múltiplas linhas)
    '''Observação:\s*Havendo\s+necessidade\s+de\s+confronto\s+das\s+impressões\s+apostas[\s\S]*?caráter\s+científico\.''',
    # Bloco do Tribunal (múltiplas linhas)
    '''Tribunal\s+de\s+Justiça\s+do\s+Estado\s+de\s+Goiás\s+Documento\s+Assinado\s+e\s+Publicado\s+Digitalmente.*?https://projudi\.tjgo\.jus\.br/\w+''',
    # Componentes individuais do bloco do Tribunal
    '''Documento\s+Assinado\s+e\s+Publicado\s+Digitalmente\s+em\s+\d{2}/\d{2}/\d{4}\s+\d{2}:\d{2}:\d{2}''',
    '''Assinado\s+por\s+[A-ZÀ-Ú\s]+(?:\s+[A-ZÀ-Ú]+)*''',
    '''Localizar\s+pelo\s+código:\s*\d+,\s*no\s+endereço:\s*https?://\S+''',
]

[paginacao]
patterns = [
    "---\\s*Página\\s+\\d+\\s*---",
    "Página\\s+\\d+\\s+de\\s+\\d+"
]

[rodape_links]
patterns = [
    "https?://raivirtual\\.ssp\\.go\\.gov\\.br\\S*",
    "CÓDIGO\\s+DE\\s+VALIDAÇÃO:\\s*[a-fA-F0-9]+"
]

[separadores]
patterns = [
    "[_\\-=*]{8,}",
    "[.]{8,}"
]

[configuracoes]
ordem_processamento = [
    "metadados_processuais",
    "assinaturas_digitais",
    "cabecalhos_institucionais",
    "textos_margem_rotacionados",
    "rodape_institucional",
    "rodape_links",
    "paginacao",
    "separadores"
]

normalizar_espacos = true
remover_linhas_vazias_excessivas = true
aplicar_correcao_caracteres = false
max_linhas_vazias_consecutivas = 0
min_tamanho_linha_util = 2